name: Packing

on:
  release:
    types: [published]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-upload:
    name: Build and upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Install packages
        shell: bash
        run: |
          sudo apt-get update && sudo apt-get install curl build-essential gcc fontconfig libfontconfig-dev libfreetype-dev

      - name: Install Rust
        shell: bash
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          . "$HOME/.cargo/env"

      - name: Build binary
        shell: bash
        run: |
          cargo build --release

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Image
        shell: bash
        run: |
          docker build -t liki4_teloxide_bot:$VERSION --output=type=docker .
          docker save liki4_teloxide_bot:$VERSION > liki4_teloxide_bot_$VERSION.tar
          echo "IMAGE=liki4_teloxide_bot_$VERSION.tar" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/liki4_teloxide_bot
            ${{ env.IMAGE }}